name: Development Pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jabberpoint-package
          path: target/*.jar

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: jabberpoint-package
      - name: Deploy to Development
        run: |
          echo "Deploying to Development environment"
          # Here you would add the actual commands to deploy to your dev environment
          # For example:
          # - Copy files to dev server
          # - Restart services
          # - Run database migrations